INSERT INTO Avaliacao (id_cliente, avaliacao, comentario, visibilidade) VALUES
('C10002', 5,    'Top service, will return!',                        1),
('C10011', 5,    'Best beers I have tried in the city.',              1),
('C10023', 4,    'Good, but the music was too loud.',                1),
('C10027', 3,    NULL,                                                0),
('C10034', 5,    NULL,                                                1),
('C10047', 5,    'Amazing snacks and great vibe.',                   1),
('C10056', 5,    NULL,                                                1),
('C10059', 4,    'Nice place, friendly staff.',                      1),
('C10066', 2,    NULL,                                                0),
('C10071', 1,    'Disappointing, beer tasted stale.',                0),
('C10075', 5,    NULL,                                                1),
('C10081', 5,    'Muito bom!',                                       1),
('C10090', 5,    NULL,                                                1),
('C10098', 4,    NULL,                                                1),
('C10105', 3,    NULL,                                                0),
('C10111', 4,    'Bera chilled, love the terrace.',                  1),
('C10125', 5,    'Sensational service.',                             1),
('C10137', 5,    NULL,                                                1),
('C10141', 4,    NULL,                                                1),
('C10159', 5,    'Perfect! Highly recommend.',                       1),
('C10165', 5,    NULL,                                                1),
('C10166', 5,    'Staff were attentive and quick.',                  1),
('C10173', 5,    NULL,                                                1),
('C10178', 2,    'Too crowded when I visited.',                      0),
('C10186', 4,    'Lovely decor and atmosphere.',                     1),
('C10197', 5,    NULL,                                                1),
('C10200', 5,    NULL,                                                1),
('C10008', 5,    NULL,                                                1),
('C10019', 4,    'Bons preços e cervejas!',                          1),
('C10041', 5,    'Will recommend to friends.',                       1),
('C10052', 5,    NULL,                                                1),
('C10089', 5,    NULL,                                                1),
('C10112', 1,    NULL,                                                0),
('C10128', 3,    NULL,                                                0),
('C10139', 5,    'Really enjoyed the snacks.',                       1),
('C10192', 4,    NULL,                                                1);